### ISSUE TITLE
Cant build for Windows

### ISSUE THREAD

**Issue by ZilchofNowhere** [Hornet07/Magma#1]
I first do `cmake .` in the cloned folder and then build the outcoming solution with VS2022 but it says `glm/glm.h not found` even after installing the package using `vcpkg`. Please make it possible to build on Windows and add instructions to build if possible.

**Comment by Hornet07** [comment]
Added manual dependency path options and pushed some default files for glm and GLFW
I believe CMake can find the Vulkan package as the SDK is installed via a installer on Windows
-DDEPS /path/to/deps

**Comment by Hornet07** [comment]
no response closing issue
